import '../../data/models/workout_template_model.dart';

class WorkoutTemplateCatalog {
  static const List<String> categories = ['Abs', 'Arm', 'Chest', 'Leg', 'Shoulder', 'Full Body'];

  static const List<WorkoutTemplate> challenges = [
    WorkoutTemplate(
      id: 'ch_full_body_shred',
      name: 'Full Body Shred',
      category: 'Full Body',
      durationMinutes: 35,
      difficulty: 3,
      isChallenge: true,
      description: 'A single focused circuit hitting every major muscle group.',
      tags: ['No Equipment', 'Full Body'],
      exercises: [
        WorkoutTemplateExercise(name: 'Squats', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Push-ups', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Deadlifts', sets: 3, reps: 10),
        WorkoutTemplateExercise(name: 'Plank', sets: 3, reps: 1),
        WorkoutTemplateExercise(name: 'Lunges', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Burpees', sets: 3, reps: 10),
        WorkoutTemplateExercise(name: 'Mountain Climbers', sets: 3, reps: 20),
        WorkoutTemplateExercise(name: 'Bicep Curls', sets: 3, reps: 12),
      ],
    ),
    WorkoutTemplate(
      id: 'ch_core_burn',
      name: 'Core Burn Circuit',
      category: 'Abs',
      durationMinutes: 20,
      difficulty: 2,
      isChallenge: true,
      description: 'Fast-paced core circuit — no rest between exercises.',
      tags: ['No Equipment', 'Core Focus'],
      exercises: [
        WorkoutTemplateExercise(name: 'Plank', sets: 3, reps: 1),
        WorkoutTemplateExercise(name: 'Bicycle Crunches', sets: 3, reps: 20),
        WorkoutTemplateExercise(name: 'Russian Twists', sets: 3, reps: 20),
        WorkoutTemplateExercise(name: 'Leg Raises', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Mountain Climbers', sets: 3, reps: 20),
        WorkoutTemplateExercise(name: 'V-Ups', sets: 3, reps: 12),
      ],
    ),
  ];

  static const List<WorkoutTemplate> templates = [
    WorkoutTemplate(
      id: 'abs_beginner',
      name: 'Abs Beginner',
      category: 'Abs',
      durationMinutes: 15,
      difficulty: 1,
      exercises: [
        WorkoutTemplateExercise(name: 'Plank', sets: 3, reps: 1),
        WorkoutTemplateExercise(name: 'Crunches', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Leg Raises', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Russian Twists', sets: 3, reps: 15),
      ],
    ),
    WorkoutTemplate(
      id: 'abs_intermediate',
      name: 'Abs Intermediate',
      category: 'Abs',
      durationMinutes: 20,
      difficulty: 2,
      exercises: [
        WorkoutTemplateExercise(name: 'Plank', sets: 3, reps: 1),
        WorkoutTemplateExercise(name: 'Bicycle Crunches', sets: 3, reps: 20),
        WorkoutTemplateExercise(name: 'Leg Raises', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Russian Twists', sets: 3, reps: 20),
        WorkoutTemplateExercise(name: 'Mountain Climbers', sets: 3, reps: 20),
      ],
    ),
    WorkoutTemplate(
      id: 'abs_advanced',
      name: 'Abs Advanced',
      category: 'Abs',
      durationMinutes: 25,
      difficulty: 3,
      exercises: [
        WorkoutTemplateExercise(name: 'Weighted Plank', sets: 3, reps: 1),
        WorkoutTemplateExercise(name: 'V-Ups', sets: 4, reps: 15),
        WorkoutTemplateExercise(name: 'Hanging Leg Raises', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Russian Twists', sets: 4, reps: 20),
        WorkoutTemplateExercise(name: 'Mountain Climbers', sets: 3, reps: 25),
        WorkoutTemplateExercise(name: 'Ab Wheel Rollout', sets: 3, reps: 10),
      ],
    ),
    WorkoutTemplate(
      id: 'arm_beginner',
      name: 'Arm Beginner',
      category: 'Arm',
      durationMinutes: 16,
      difficulty: 1,
      exercises: [
        WorkoutTemplateExercise(name: 'Bicep Curls', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Tricep Dips', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Overhead Tricep Extension', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Hammer Curls', sets: 3, reps: 12),
      ],
    ),
    WorkoutTemplate(
      id: 'arm_intermediate',
      name: 'Arm Intermediate',
      category: 'Arm',
      durationMinutes: 22,
      difficulty: 2,
      exercises: [
        WorkoutTemplateExercise(name: 'Bicep Curls', sets: 4, reps: 12),
        WorkoutTemplateExercise(name: 'Close-Grip Push-ups', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Tricep Dips', sets: 4, reps: 15),
        WorkoutTemplateExercise(name: 'Hammer Curls', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Concentration Curls', sets: 3, reps: 10),
      ],
    ),
    WorkoutTemplate(
      id: 'arm_advanced',
      name: 'Arm Advanced',
      category: 'Arm',
      durationMinutes: 28,
      difficulty: 3,
      exercises: [
        WorkoutTemplateExercise(name: 'Bicep Curls', sets: 4, reps: 12),
        WorkoutTemplateExercise(name: 'Skull Crushers', sets: 4, reps: 12),
        WorkoutTemplateExercise(name: 'Close-Grip Push-ups', sets: 4, reps: 15),
        WorkoutTemplateExercise(name: '21s Bicep Curls', sets: 3, reps: 21),
        WorkoutTemplateExercise(name: 'Tricep Dips', sets: 4, reps: 15),
      ],
    ),
    WorkoutTemplate(
      id: 'chest_beginner',
      name: 'Chest Beginner',
      category: 'Chest',
      durationMinutes: 15,
      difficulty: 1,
      exercises: [
        WorkoutTemplateExercise(name: 'Push-ups', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Incline Push-ups', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Chest Fly', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Bench Press', sets: 3, reps: 10),
      ],
    ),
    WorkoutTemplate(
      id: 'chest_intermediate',
      name: 'Chest Intermediate',
      category: 'Chest',
      durationMinutes: 22,
      difficulty: 2,
      exercises: [
        WorkoutTemplateExercise(name: 'Bench Press', sets: 4, reps: 10),
        WorkoutTemplateExercise(name: 'Decline Push-ups', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Chest Fly', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Cable Crossover', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Push-ups', sets: 3, reps: 15),
      ],
    ),
    WorkoutTemplate(
      id: 'chest_advanced',
      name: 'Chest Advanced',
      category: 'Chest',
      durationMinutes: 28,
      difficulty: 3,
      exercises: [
        WorkoutTemplateExercise(name: 'Bench Press', sets: 5, reps: 8),
        WorkoutTemplateExercise(name: 'Weighted Dips', sets: 4, reps: 10),
        WorkoutTemplateExercise(name: 'Plyo Push-ups', sets: 3, reps: 10),
        WorkoutTemplateExercise(name: 'Cable Crossover', sets: 4, reps: 12),
        WorkoutTemplateExercise(name: 'Chest Fly', sets: 3, reps: 12),
      ],
    ),
    WorkoutTemplate(
      id: 'leg_beginner',
      name: 'Leg Beginner',
      category: 'Leg',
      durationMinutes: 18,
      difficulty: 1,
      exercises: [
        WorkoutTemplateExercise(name: 'Bodyweight Squats', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Lunges', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Glute Bridges', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Calf Raises', sets: 3, reps: 20),
      ],
    ),
    WorkoutTemplate(
      id: 'leg_intermediate',
      name: 'Leg Intermediate',
      category: 'Leg',
      durationMinutes: 25,
      difficulty: 2,
      exercises: [
        WorkoutTemplateExercise(name: 'Squats', sets: 4, reps: 12),
        WorkoutTemplateExercise(name: 'Bulgarian Split Squats', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Step-ups', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Glute Bridges', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Calf Raises', sets: 3, reps: 20),
      ],
    ),
    WorkoutTemplate(
      id: 'leg_advanced',
      name: 'Leg Advanced',
      category: 'Leg',
      durationMinutes: 32,
      difficulty: 3,
      exercises: [
        WorkoutTemplateExercise(name: 'Squats', sets: 5, reps: 10),
        WorkoutTemplateExercise(name: 'Jump Squats', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Pistol Squats', sets: 3, reps: 6),
        WorkoutTemplateExercise(name: 'Bulgarian Split Squats', sets: 4, reps: 12),
        WorkoutTemplateExercise(name: 'Calf Raises', sets: 4, reps: 20),
      ],
    ),
    WorkoutTemplate(
      id: 'shoulder_beginner',
      name: 'Shoulder Beginner',
      category: 'Shoulder',
      durationMinutes: 15,
      difficulty: 1,
      exercises: [
        WorkoutTemplateExercise(name: 'Shoulder Press', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Lateral Raises', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Front Raises', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Shrugs', sets: 3, reps: 15),
      ],
    ),
    WorkoutTemplate(
      id: 'shoulder_intermediate',
      name: 'Shoulder Intermediate',
      category: 'Shoulder',
      durationMinutes: 20,
      difficulty: 2,
      exercises: [
        WorkoutTemplateExercise(name: 'Arnold Press', sets: 4, reps: 12),
        WorkoutTemplateExercise(name: 'Lateral Raises', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Rear Delt Fly', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Front Raises', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Shrugs', sets: 3, reps: 15),
      ],
    ),
    WorkoutTemplate(
      id: 'shoulder_advanced',
      name: 'Shoulder Advanced',
      category: 'Shoulder',
      durationMinutes: 26,
      difficulty: 3,
      exercises: [
        WorkoutTemplateExercise(name: 'Shoulder Press', sets: 5, reps: 10),
        WorkoutTemplateExercise(name: 'Handstand Push-ups', sets: 3, reps: 6),
        WorkoutTemplateExercise(name: 'Upright Rows', sets: 4, reps: 12),
        WorkoutTemplateExercise(name: 'Lateral Raises', sets: 4, reps: 15),
        WorkoutTemplateExercise(name: 'Rear Delt Fly', sets: 3, reps: 12),
      ],
    ),
    WorkoutTemplate(
      id: 'fullbody_beginner',
      name: 'Full Body Beginner',
      category: 'Full Body',
      durationMinutes: 20,
      difficulty: 1,
      exercises: [
        WorkoutTemplateExercise(name: 'Squats', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Push-ups', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Bent-over Rows', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Plank', sets: 3, reps: 1),
      ],
    ),
    WorkoutTemplate(
      id: 'fullbody_intermediate',
      name: 'Full Body Intermediate',
      category: 'Full Body',
      durationMinutes: 28,
      difficulty: 2,
      exercises: [
        WorkoutTemplateExercise(name: 'Squats', sets: 4, reps: 12),
        WorkoutTemplateExercise(name: 'Push-ups', sets: 3, reps: 15),
        WorkoutTemplateExercise(name: 'Lunges', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Bent-over Rows', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Burpees', sets: 3, reps: 10),
      ],
    ),
    WorkoutTemplate(
      id: 'fullbody_advanced',
      name: 'Full Body Advanced',
      category: 'Full Body',
      durationMinutes: 35,
      difficulty: 3,
      exercises: [
        WorkoutTemplateExercise(name: 'Deadlifts', sets: 4, reps: 8),
        WorkoutTemplateExercise(name: 'Thrusters', sets: 4, reps: 10),
        WorkoutTemplateExercise(name: 'Push-ups', sets: 4, reps: 15),
        WorkoutTemplateExercise(name: 'Burpees', sets: 3, reps: 12),
        WorkoutTemplateExercise(name: 'Plank', sets: 3, reps: 1),
      ],
    ),
  ];

  static List<WorkoutTemplate> byCategory(String category) {
    return templates.where((t) => t.category == category).toList();
  }
}