// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Q0hzjM-bMuj3P3oaFyEov-oZtYMIzDQ',
    appId: '1:366208969986:web:e0d579540388f6fc5e261b',
    messagingSenderId: '366208969986',
    projectId: 'workout-logger-270db',
    authDomain: 'workout-logger-270db.firebaseapp.com',
    storageBucket: 'workout-logger-270db.firebasestorage.app',
    measurementId: 'G-RMZE05ZLSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6NqCvbtNBKNKMx7gaQDPQRUGju1pgXp4',
    appId: '1:366208969986:android:1dbeb7a95d5791e75e261b',
    messagingSenderId: '366208969986',
    projectId: 'workout-logger-270db',
    storageBucket: 'workout-logger-270db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmRuet_iyaJo8p51eepkw3U5WfLF9g4KY',
    appId: '1:366208969986:ios:1aa19975543f953a5e261b',
    messagingSenderId: '366208969986',
    projectId: 'workout-logger-270db',
    storageBucket: 'workout-logger-270db.firebasestorage.app',
    iosBundleId: 'com.example.workoutLogger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Q0hzjM-bMuj3P3oaFyEov-oZtYMIzDQ',
    appId: '1:366208969986:web:1a9702e63668f2bd5e261b',
    messagingSenderId: '366208969986',
    projectId: 'workout-logger-270db',
    authDomain: 'workout-logger-270db.firebaseapp.com',
    storageBucket: 'workout-logger-270db.firebasestorage.app',
    measurementId: 'G-76P8338183',
  );
}
